[package]
edition = "2024"
name = "api"
version = "0.1.0"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
types.workspace = true
uuid.workspace = true

server = { workspace = true, optional = true }

[features]
server = ["dioxus/server", "types/server", "dep:server"]
